# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

---
  pool: Default
  
  trigger: none
  
  pr:
    - main
    
  steps:
    - task: JFrogMaven@1
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'install'
        artifactoryResolverService: 'JFROG_CLOUD'
        targetResolveReleaseRepo: 'spring_petclinic-libs-release'
        targetResolveSnapshotRepo: 'spring_petclinic-libs-snapshot'
        artifactoryDeployService: 'JFROG_CLOUD'
        targetDeployReleaseRepo: 'spring_petclinic-libs-release'
        targetDeploySnapshotRepo: 'spring_petclinic-libs-snapshot'
        javaHomeOption: 'JDKVersion'
    - task: JFrogPublishBuildInfo@1
      inputs:
        artifactoryConnection: 'JFROG_CLOUD'
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'